# REUSE Software Bill of Materials
# https://reuse.software/
version = 1
SPDX-PackageName = "testing"
SPDX-PackageSupplier = "Byron Williams"
SPDX-PackageDownloadLocation = "https://github.com/williaby/testing"

[[annotations]]
path = ["**"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "2025 Byron Williams"
